version: '3'

services:
  postgres:
    image: 'postgres:14.2'
    ports:
      - '5431:5432'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product-subscription
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
